component_depth: 8
languages:
- name: java
  production:
    exclude:
      - .*/test/java/de/datasecs/hydra/.*\.java
  test:
    include:
      - .*/test/java/de/datasecs/hydra/.*\.java

exclude:
- .*/Packet\.java
- /example/.*