language: java

sudo: false

install: "mvn -P ci clean install"
script: "mvn -P ci clean compile test cobertura:cobertura"

os:
- linux
- osx

jdk:
- oraclejdk8
- oraclejdk10
- openjdk11
- openjdk-ea

matrix:
  exclude:
  - os: osx
    jdk: oraclejdk8
  - os: osx
    jdk: oraclejdk10

after_success:
- bash < (curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
