language: java

install: "mvn -P ci clean install"
script: "mvn -P ci clean compile test cobertura:cobertura"

os:
- linux
- osx

jdk:
- oraclejdk8
- oraclejdk10
- openjdk11

matrix:
  allow_failures:
    - os: osx
      jdk: oraclejdk10
      jdk: oraclejdk8
    - jdk: openjdk11

after_success:
- bash < (curl -s https://codecov.io/bash)