language: java

install: "mvn clean compile test --pl \!de.datasecs:hydra-all,\!de.datasecs:hydra-example"
script: "mvn -P ci clean compile test"

os:
- linux
- osx

jdk:
- oraclejdk8
- oraclejdk10
- openjdk11

after_success:
- bash < (curl -s https://codecov.io/bash)